add 'export-tarball' and use that from build-deb.
This pulls in some tool cleanups that I did for curtin.
the export-tarball is nice to be able to cleanly export a nicely
named tarball of trunk or of a tag.  And then build-deb just uses
that.

The move of changelog to changelog.trunk to is allow trunk to have
its own changelog and not conflict with packaged versions.

bzr-revno: 312

diff --git a/tools/build-deb b/tools/build-deb
--- a/tools/build-deb
+++ b/tools/build-deb
@@ -1,5 +1,7 @@
 #!/bin/sh
 
+set -e
+
 sourcename="simplestreams"
 TEMP_D=""
 UNCOMMITTED=${UNCOMMITTED:-0}
@@ -30,16 +32,10 @@ bname=${0##*/}
 start_d=$PWD
 top_d=$(cd "$(dirname "${0}")"/.. && pwd)
 
-export_uncommitted=""
-echo $UNCOMMITTED
-if [ "${UNCOMMITTED:-0}" != "0" ]; then
-   export_uncommitted="--uncommitted"
-fi
-
 # grab the first line in the changelog
 # hopefully this pulls the version info there
 # resulting in something like: 0.1.0~bzrREVNO-1~trunk1
-clogver_o=$(sed -n '1s,.*(\([^)]*\)).*,\1,p' debian/changelog)
+clogver_o=$(sed -n '1s,.*(\([^)]*\)).*,\1,p' debian/changelog.trunk)
 
 revno=$(bzr revno) || fail "failed to get revno"
 clogver_upstream=${clogver_o%%-*}
@@ -57,19 +53,22 @@ echo "building upstream version $uver, debian ver=${clogver_debian}"
 dir="${sourcename}-$uver"
 tarball="${sourcename}_$uver.orig.tar.gz"
 
-echo bzr export --format=tgz --root="$dir" --revision="${revno}" \
-   ${export_uncommitted} "${TEMP_D}/$tarball"
-bzr export --format=tgz --root="$dir" --revision="${revno}" \
-   ${export_uncommitted} "${TEMP_D}/$tarball" ||
-   fail "failed to bzr export tarball $tarball"
+myd=$(dirname "$0")
+"$myd/export-tarball" "${revno}" "${TEMP_D}/$tarball"
 echo "created ${tarball}"
 
-cd ${TEMP_D}
+cd "${TEMP_D}"
 tar xzf "$tarball" || fail "failed extract tarball"
-cd "$dir" || fail "fialed cd $dir"
+cd "$dir" || fail "failed cd $dir"
+
+# move files ending in .trunk to name without .trunk
+# ie, this copies debian/changelog.trunk to debian/changelog
+for f in debian/*.trunk; do
+   mv "$f" "${f%.trunk}"
+done
 
 sed -i "1s,${clogver_o},${clogver_new}," debian/changelog ||
-   fail "failed to change replace REVNO in debian/changelog"
+   fail "failed to write debian/changelog"
 debuild "$@" || fail "debuild failed"
 
 cd "$TEMP_D"
