hook-glance: working towards new format.
bzr-revno: 159

diff --git a/tools/hook-glance b/tools/hook-glance
--- a/tools/hook-glance
+++ b/tools/hook-glance
@@ -4,9 +4,15 @@ set -f
 RC_FILTER_INCLUDE=0
 RC_FILTER_EXCLUDE=1
 RC_FAIL=2
+VERBOSITY=${VERBOSITY:-0}
 
 error() { echo "$@" 1>&2; }
 fail() { [ $# -eq 0 ] || error "$@"; exit "$RC_FAIL"; }
+debug() {
+    [ "${VERBOSITY}" -lt "$1" ] && return
+    shift
+    error "$@"
+}
 
 Usage() {
    cat <<EOF
@@ -16,15 +22,15 @@ Usage: ${0##*/}
   It uses the 'glance' command to synchronize the remote source
   with the a glance server.
 
-  sstream-sync "--hook=$0" \
-     http://cloud-images.ubuntu.com/eightprotons/images/ v1/streams.yaml
+  sstream-sync "--hook=$0" \\
+     http://cloud-images.ubuntu.com/eightprotons/ streams/v1/index.js
 EOF
 }
 
 required() {
     local req="" missing=""
     for req in "$@"; do
-        [ -z "${!req}" ] || missing="${missing} ${req}"
+        [ -n "${!req}" ] || missing="${missing} ${req}"
     done
     missing=${missing# }
     _RET="$missing"
@@ -41,74 +47,101 @@ run() {
     return $ret
 }
 
-stream_load() {
-    local output="" ids="" id=""
-    output=$(run glance image-list "--property-filter=iqn=$iqn") || fail
+load_products() {
+    required content_id ||
+        fail "load_products missing required fields: $_RET"
+    local output="" ids="" id="" prod="" ver=""
+    output=$(run glance image-list \
+        "--property-filter=content_id=${content_id}") || fail
     ids=$(echo "$output" | awk '$2 ~ uuid { print $2 }' "uuid=[0-9a-f-]{36}")
     for id in $ids; do
         out=$(run glance image-show "$id") || fail "failed to show image $id"
-        serial=$(echo "$out" |
+        prod=$(echo "$out" |
             awk '$2 == "Property" && $3 == sname { print $5 }'
-                sname="'serial'")
-        [ -n "$serial" ] &&
-            fail "image-id '$id' had no 'serial' tag"
-        debug 1 "$iqn $serial $id"
+                sname="'product_name'")
+        [ -n "$prod" ] ||
+            fail "image-id '$id' had no 'product_name' tag"
+
+        ver=$(echo "$out" |
+            awk '$2 == "Property" && $3 == sname { print $5 }'
+                sname="'version_name'")
+        [ -n "$ver" ] ||
+            fail "image-id '$id' had no 'version_name' tag"
+
+        debug 1 "${content_id}/${prod}/${ver} ${id}"
         # report we have the given serial for this iqn
-        echo "$serial"
+        printf "%s\t%s\n" "${prod}" "${ver}"
     done
     return 0
 }
 
 
-item_insert() {
-    required iqn serial path_local arch ||
+insert_item() {
+    required content_id product_name version_name item_name arch path_local ||
         fail "missing required fields: $_RET"
 
-    local xname="${pubname:-${name##*/}}"
-    run glance image-create --disk-format=qcow2 --container-format=bare \
-          "--name=$xname" \
-          ${arch:+"--property=architecture=${arch}"} \
-          "--property=iqn=$iqn" "--property=serial=$serial" \
-          ${md5:+"--checksum=$md5"} \
-          "--file=${path_local}" ||
-        fail "failed to add image $iqn / $name"
+    local xname="${pubname:-${name}}"
+    local id="${content_id}/${product_name}/${version_name}/${item_name}"
+
+    [ -z "$pubname" ] && xname="$id"
+
+    local p="" props="" architecture="$arch"
+    propargs=()
+    for p in content_id product_name version_name item_name architecture; do
+        props[${#props[@]}]="--property=$p=${!p}"
+    done
+
+    run glance image-create \
+        --disk-format=qcow2 --container-format=bare \
+        "--name=$xname" ${md5:+"--checksum=$md5"} \
+        "${propargs[@]}" \
+        "--file=${path_local}" ||
+        fail "failed to add image $id / $xname"
 }
 
 
-group_remove_pre() {
-    required iqn serial ||
+remove_version() {
+    required content_id product_name version_name ||
         fail "missing required fields: $_RET"
 
-    local output="" ids=""
-    output=$(run glance image-list "--property-filter=iqn=$iqn" \
-                 "--property-filter=serial=$serial") ||
-    fail "failed to list images with $iqn and $serial"
+    local output="" id="" ids=""
+    local disp_info="${content_id}/${product_name}/${version_name}"
+    output=$(run glance image-list \
+        "--property-filter=content_id=${content_id}" \
+        "--property-filter=product_name=${product_name}" \
+        "--property-filter=version_name=${version_name}") ||
+    fail "failed to list images with '${disp_info}'"
     
     ids=$(echo "$output" | awk '$2 ~ uuid { print $2 }' "uuid=[0-9a-f-]{36}")
     for id in $ids; do
-        debug 1 "remove $iqn $serial $id"
-        run glance image-delete "$id" ||
-            fail "failed to remove $id"
+        debug 1 "remove ${disp_info}: $id"
+        run glance image-delete "$id" || fail "failed to remove $id"
     done
     return 0
 }
 
 
-item_filter() {
-    case "$name" in
-        *-disk1.img) return "${RC_FILTER_INCLUDE}";;
+filter_item() {
+    case "${ftype:-unknown}" in
+        unknown|disk1.img) return "${RC_FILTER_INCLUDE}";;
         *) return "${RC_FILTER_EXCLUDE}"
     esac
 }
 
 
-stream_filter() {
-    return "${RC_FILTER_INCLUDE}"
+filter_product() {
+    case "${arch:-unknown}" in
+        unknown|amd64|x86_64|i386) return "${RC_FILTER_INCLUDE}";;
+    esac
+    return "${RC_FILTER_EXCLUDE}"
 }
 
 
-group_filter() {
-    return "${RC_FILTER_INCLUDE}"
+filter_index_entry() {
+    case "${content_id}" in
+       *:download) return "${RC_FILTER_INCLUDE}";;
+       *) return "${RC_FILTER_EXCLUDE}";;
+    esac
 }
 
 
@@ -128,14 +161,14 @@ main() {
    
     # we only operate on
     case "$HOOK" in
-        item_filter|item_insert|\
-        group_filter|group_remove_pre|\
-        stream_filter|stream_load)
+        filter_item|filter_index_entry|filter_product|\
+        insert_item|load_products)
             "$HOOK";;
+        filter_*) return "${RC_FILTER_INCLUDE}";;
         *) noop;;
     esac
-    exit $?
 }
 main "$@"
+exit $?
 
 # vi: ts=4 expandtab
